name: Tanks-On-Sale-Notifier
on:
  push:
  schedule:
    - cron: '1 * * * *'
jobs:
  Check-Latest-Tanks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: ls .
      - run: pwd
