name: Tanks-On-Sale-Notifier
on:
  push:
  schedule:
    - cron: '1 * * * *'
jobs:
  Check-Latest-Tanks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go mod download
      - run: pwd
      - uses: actions/download-artifact@v2
        with:
          name: tanks-info
          path: /home/runner/work/Tanks-On-Sale-Notifier/Tanks-On-Sale-Notifier/artifact/tanks-info
      - run: go run get.go
      - uses: actions/upload-artifact@v2
        with:
          name: tanks-info
          path: /home/runner/work/Tanks-On-Sale-Notifier/Tanks-On-Sale-Notifier/artifact/tanks-info